name: docker

on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: resolve image name
        id: image
        run: |
          echo "image_name=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

      - name: docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: setup buildx
        uses: docker/setup-buildx-action@v3

      - name: resolve tag
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            echo "tag=$TAG" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.head_commit.message }}" == *"[nightly]"* ]]; then
            echo "tag=nightly" >> $GITHUB_OUTPUT
          else
            echo "skip=true" >> $GITHUB_OUTPUT
          fi

      - name: skip build
        if: steps.vars.outputs.skip == 'true'
        run: echo "no docker build required"

      - name: build and push
        if: steps.vars.outputs.skip != 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.image.outputs.image_name }}:${{ steps.vars.outputs.tag }}